name: Deploy to S3 per Branch

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: List build output
        run: |
          echo "Contents of dist directory:"
          ls -la ./dist/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set target S3 path based on branch
        id: path
        run: |
          echo "branch-name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "s3-path=s3://lenshero-plugin-assets/public/${GITHUB_REF##*/}/" >> $GITHUB_OUTPUT

      - name: Sync build files to S3
        run: |
          aws s3 cp ./dist/lenshero-widget.js ${{ steps.path.outputs.s3-path }}lenshero-widget.js
          aws s3 cp ./dist/lenshero-widget.css ${{ steps.path.outputs.s3-path }}lenshero-widget.css
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/public/${GITHUB_REF##*/}/lenshero-widget.js" "/public/${GITHUB_REF##*/}/lenshero-widget.css"
